# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{beast3}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Chien Kuo"]
  s.date = %q{2010-12-21}
  s.description = %q{An engine that enable forum feature for your website.}
  s.email = %q{chien.cc.kuo@gmail.com}
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README"
  ]
  s.files = [
    "lib/ability.rb",
    "lib/beast3.rb",
    "lib/beast3/engine.rb",
    "lib/editable.rb",
    "lib/html_formatting.rb"
  ]
  s.homepage = %q{http://nowhere}
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Rails 3 version of altered beast}
  s.test_files = [
    "spec/controllers/forums_controller_spec.rb",
    "spec/controllers/forums_sessions_and_cookies_spec.rb",
    "spec/controllers/moderatorships_controller_spec.rb",
    "spec/controllers/monitorships_controller_spec.rb",
    "spec/controllers/posts_controller_spec.rb",
    "spec/controllers/sessions_controller_spec.rb",
    "spec/controllers/topics_controller_spec.rb",
    "spec/controllers/users_controller_spec.rb",
    "spec/helpers/forums_helper_spec.rb",
    "spec/helpers/users_helper_spec.rb",
    "spec/model_stubs.rb",
    "spec/models/forum_spec.rb",
    "spec/models/moderatorship_spec.rb",
    "spec/models/monitorship_spec.rb",
    "spec/models/post_spec.rb",
    "spec/models/topic_spec.rb",
    "spec/models/user_posting_spec.rb",
    "spec/models/user_spec.rb",
    "spec/spec_helper.rb"
  ]

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rails>, ["= 3.0.3"])
      s.add_runtime_dependency(%q<haml>, [">= 0"])
      s.add_runtime_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_runtime_dependency(%q<devise>, ["= 1.1.5"])
      s.add_runtime_dependency(%q<acts_as_list>, [">= 0"])
      s.add_runtime_dependency(%q<has_permalink>, [">= 0"])
      s.add_runtime_dependency(%q<cancan>, [">= 0"])
      s.add_runtime_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_runtime_dependency(%q<RedCloth>, [">= 0"])
      s.add_development_dependency(%q<shoulda>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_development_dependency(%q<rcov>, [">= 0"])
      s.add_development_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<rspec-rails>, [">= 0"])
      s.add_development_dependency(%q<ruby-debug>, [">= 0"])
      s.add_runtime_dependency(%q<rails>, ["= 3.0.3"])
      s.add_runtime_dependency(%q<devise>, ["= 1.1.5"])
      s.add_runtime_dependency(%q<cancan>, ["= 1.4.1"])
      s.add_runtime_dependency(%q<will_paginate>, ["= 3.0.pre2"])
      s.add_runtime_dependency(%q<has_permalink>, ["= 0.0.5"])
      s.add_runtime_dependency(%q<RedCloth>, ["= 4.2.3"])
      s.add_runtime_dependency(%q<acts_as_list>, ["= 0.1.2"])
      s.add_runtime_dependency(%q<haml>, ["= 3.0.24"])
    else
      s.add_dependency(%q<rails>, ["= 3.0.3"])
      s.add_dependency(%q<haml>, [">= 0"])
      s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
      s.add_dependency(%q<devise>, ["= 1.1.5"])
      s.add_dependency(%q<acts_as_list>, [">= 0"])
      s.add_dependency(%q<has_permalink>, [">= 0"])
      s.add_dependency(%q<cancan>, [">= 0"])
      s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
      s.add_dependency(%q<RedCloth>, [">= 0"])
      s.add_dependency(%q<shoulda>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
      s.add_dependency(%q<rcov>, [">= 0"])
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<rspec-rails>, [">= 0"])
      s.add_dependency(%q<ruby-debug>, [">= 0"])
      s.add_dependency(%q<rails>, ["= 3.0.3"])
      s.add_dependency(%q<devise>, ["= 1.1.5"])
      s.add_dependency(%q<cancan>, ["= 1.4.1"])
      s.add_dependency(%q<will_paginate>, ["= 3.0.pre2"])
      s.add_dependency(%q<has_permalink>, ["= 0.0.5"])
      s.add_dependency(%q<RedCloth>, ["= 4.2.3"])
      s.add_dependency(%q<acts_as_list>, ["= 0.1.2"])
      s.add_dependency(%q<haml>, ["= 3.0.24"])
    end
  else
    s.add_dependency(%q<rails>, ["= 3.0.3"])
    s.add_dependency(%q<haml>, [">= 0"])
    s.add_dependency(%q<sqlite3-ruby>, [">= 0"])
    s.add_dependency(%q<devise>, ["= 1.1.5"])
    s.add_dependency(%q<acts_as_list>, [">= 0"])
    s.add_dependency(%q<has_permalink>, [">= 0"])
    s.add_dependency(%q<cancan>, [">= 0"])
    s.add_dependency(%q<will_paginate>, ["~> 3.0.pre2"])
    s.add_dependency(%q<RedCloth>, [">= 0"])
    s.add_dependency(%q<shoulda>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.5.2"])
    s.add_dependency(%q<rcov>, [">= 0"])
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<rspec-rails>, [">= 0"])
    s.add_dependency(%q<ruby-debug>, [">= 0"])
    s.add_dependency(%q<rails>, ["= 3.0.3"])
    s.add_dependency(%q<devise>, ["= 1.1.5"])
    s.add_dependency(%q<cancan>, ["= 1.4.1"])
    s.add_dependency(%q<will_paginate>, ["= 3.0.pre2"])
    s.add_dependency(%q<has_permalink>, ["= 0.0.5"])
    s.add_dependency(%q<RedCloth>, ["= 4.2.3"])
    s.add_dependency(%q<acts_as_list>, ["= 0.1.2"])
    s.add_dependency(%q<haml>, ["= 3.0.24"])
  end
end

